<!--CUISNIER  RECUPERATIUON ET INJECTION A JSON DES  DONNEES FORMULAIRE INSCRIPTION-->



<!--Une fois que tout est sécurisé coté client et serveur alors :-->






<!--PARTICULIER  RECUPERATIUON ET INJECTIONS A JSON DONNEES FORMULAIRE INSCRIPTION-->